import React from 'react';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { venturesData } from '@/lib/data/ventures';

const staticLinks = [
  { href: '/', label: 'Home' },
  { href: '/research', label: 'Research' },
  { href: '/ventures', label: 'Ventures' },
  { href: '/build', label: 'Build' },
  { href: '/distribute', label: 'Distribute' },
  { href: '/booking', label: 'Booking' },
  { href: '/terms', label: 'Terms' },
  { href: '/privacy', label: 'Privacy' },
  { href: '/sitemap.xml', label: 'Sitemap (XML)' },
  { href: '/sitemap.md', label: 'Sitemap (Markdown)' },
];

export default function SitemapPage() {
  return (
    <div className="min-h-screen text-zinc-900 dark:text-zinc-100 font-sans transition-colors duration-300 overflow-x-hidden">
      <Navbar />

      <main className="max-w-5xl mx-auto px-6 md:px-12 py-20">
        <header className="mb-12">
          <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight">Sitemap</h1>
          <p className="mt-3 text-zinc-500 dark:text-zinc-400 max-w-2xl text-sm">
            A human-friendly index of the site's pages and main endpoints. Use this as a navigation aid or reference.
          </p>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
          <div className="col-span-2">
            <h2 className="text-lg font-semibold mb-4">Main Navigation</h2>
            <div className="grid sm:grid-cols-2 gap-3">
              {staticLinks.map((l) => (
                <Link key={l.href} href={l.href} className="block p-3 rounded-lg bg-zinc-50 dark:bg-black/20 border border-black/5 dark:border-white/5 hover:shadow-sm transition-shadow">
                  <span className="font-medium text-zinc-900 dark:text-zinc-100">{l.label}</span>
                  <div className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">{l.href}</div>
                </Link>
              ))}
            </div>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-4">Quick Actions</h2>
            <div className="flex flex-col gap-3">
              <Link href="/booking" className="px-4 py-3 bg-zinc-900 text-white rounded-lg text-sm text-center hover:bg-zinc-800 transition-colors">Schedule a call</Link>
              <a href="/sitemap.xml" className="px-4 py-3 border rounded-lg text-sm text-zinc-700 dark:text-zinc-200 text-center hover:bg-zinc-50 dark:hover:bg-white/5 transition-colors">Download XML</a>
              <a href="/sitemap.md" className="px-4 py-3 border rounded-lg text-sm text-zinc-700 dark:text-zinc-200 text-center hover:bg-zinc-50 dark:hover:bg-white/5 transition-colors">View Markdown</a>
            </div>
          </div>
        </section>

        <section className="mb-16">
          <h2 className="text-lg font-semibold mb-4">Research / Case Studies</h2>
          <div className="grid gap-4">
            {venturesData.map((v) => (
              <article key={v.id} className="p-4 rounded-lg bg-zinc-50 dark:bg-black/20 border border-black/5 dark:border-white/5">
                <Link href={`/research/${v.id}`} className="flex items-start justify-between gap-4">
                  <div>
                    <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">{v.title}</h3>
                    <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">{v.description}</p>
                  </div>
                  <div className="text-xs text-zinc-400 dark:text-zinc-500">/research/{v.id}</div>
                </Link>
              </article>
            ))}
          </div>
        </section>

        <section className="mb-20">
          <h2 className="text-lg font-semibold mb-4">External & Project Links</h2>
          <div className="grid gap-3">
            {venturesData.map((v) => (
              <div key={v.id} className="flex items-center justify-between p-3 rounded-lg bg-zinc-50 dark:bg-black/20 border border-black/5 dark:border-white/5">
                <div>
                  <div className="text-sm font-medium text-zinc-900 dark:text-zinc-100">{v.title}</div>
                  <div className="text-xs text-zinc-500 dark:text-zinc-400">Build: <a href={v.links.build} target="_blank" rel="noreferrer" className="underline">{v.links.build}</a></div>
                </div>
                <div className="text-xs text-zinc-400 dark:text-zinc-500">External</div>
              </div>
            ))}
          </div>
        </section>

        <footer className="pt-8">
          <p className="text-xs text-zinc-500 dark:text-zinc-400">If you'd like a different export format or want this autogenerated into a robots-friendly feed, let us know.</p>
        </footer>
      </main>

      <Footer />
    </div>
  );
}
